(function(S, I){
    I.TimeReportsController = ["$scope", "scanner", "timeReportManager", function($scope, scanner, timeReportManager) {

        $scope.changeHeader({
            header: "TimeReports",
            home: true
        });
        
        timeReportManager.getTimeReports().then(
            function(reports) {
                //$scope.reports = reports;
                $scope.reports = [
                    {
                        "UniqueId": "f9c9e875-c211-4b43-b4a0-b5ea4750df7c",
                        "Date": "2014-04-02T13:38:06.111Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 0
                    },
                    {
                        "UniqueId": "492eb1d3-1a9e-4e2e-b7eb-52a51171abba",
                        "Date": "2014-04-02T13:42:17.311Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 1
                    },
                    {
                        "UniqueId": "6f2d3825-c61b-4113-85f6-399b130b7a6f",
                        "Date": "2014-04-02T13:43:30.622Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 2
                    },
                    {
                        "UniqueId": "ba117612-c097-4aed-8d7c-89a5a95a35e1",
                        "Date": "2014-04-02T14:24:07.351Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 3
                    },
                    {
                        "UniqueId": "5a48f276-f065-4a25-8c90-ea05c7b8ac3a",
                        "Date": "2014-04-02T15:19:34.535Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 2
                    },
                    {
                        "UniqueId": "e1cffea7-b93f-4415-afed-84a8903f169b",
                        "Date": "2014-04-02T15:27:30.053Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Site": {
                                "Id": 123,
                                "IsActive": false,
                                "Name": "עמל",
                                "SiteName": null,
                                "AllPhones": "8421630,8721003",
                                "Company": {
                                    "Id": 19,
                                    "IsActive": false,
                                    "Name": "שחף - 19",
                                    "SiteName": null,
                                    "Email": null
                                },
                                "Phones": [
                                    "8421630",
                                    "8721003"
                                ],
                                "SecurityManager": {
                                    "Id": 0,
                                    "IsActive": false,
                                    "Name": "דורון קליין",
                                    "SiteName": null,
                                    "Mobile": null,
                                    "Phone": "057-7548433"
                                },
                                "SecurityManagerName": "דורון קליין",
                                "SecurityManagerPhone": "057-7548433",
                                "StandardEndHours": [
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    null,
                                    null
                                ],
                                "StandardStartHours": [
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    null,
                                    null
                                ],
                                "Supervisor": {
                                    "Id": 0,
                                    "IsActive": false,
                                    "Name": "חיים",
                                    "SiteName": null,
                                    "Mobile": null,
                                    "Phone": "052-5251079"
                                },
                                "SupervisorName": "חיים",
                                "SupervisorPhone": "052-5251079",
                                "TimeZoneOffset": 180
                            },
                            "Date": "2014-04-02T15:26:39.873Z"
                        },
                        "Status": 2
                    },
                    {
                        "UniqueId": "ac28bcc7-cf4c-4788-98ce-3fe9ebae1a69",
                        "Date": "2014-04-02T15:28:15.702Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Site": {
                                "Id": 123,
                                "IsActive": false,
                                "Name": "עמל",
                                "SiteName": null,
                                "AllPhones": "8421630,8721003",
                                "Company": {
                                    "Id": 19,
                                    "IsActive": false,
                                    "Name": "שחף - 19",
                                    "SiteName": null,
                                    "Email": null
                                },
                                "Phones": [
                                    "8421630",
                                    "8721003"
                                ],
                                "SecurityManager": {
                                    "Id": 0,
                                    "IsActive": false,
                                    "Name": "דורון קליין",
                                    "SiteName": null,
                                    "Mobile": null,
                                    "Phone": "057-7548433"
                                },
                                "SecurityManagerName": "דורון קליין",
                                "SecurityManagerPhone": "057-7548433",
                                "StandardEndHours": [
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    null,
                                    null
                                ],
                                "StandardStartHours": [
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    null,
                                    null
                                ],
                                "Supervisor": {
                                    "Id": 0,
                                    "IsActive": false,
                                    "Name": "חיים",
                                    "SiteName": null,
                                    "Mobile": null,
                                    "Phone": "052-5251079"
                                },
                                "SupervisorName": "חיים",
                                "SupervisorPhone": "052-5251079",
                                "TimeZoneOffset": 180
                            },
                            "Date": "2014-04-02T15:26:39.873Z"
                        },
                        "Status": 2
                    },
                    {
                        "UniqueId": "de6385fb-53e5-47ba-bb18-d0b1f3a90258",
                        "Date": "2014-04-02T15:30:39.367Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 2
                    },
                    {
                        "UniqueId": "e3abe063-4b42-43fe-818d-190e28a67405",
                        "Date": "2014-04-02T15:30:52.382Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Site": {
                                "Id": 123,
                                "IsActive": false,
                                "Name": "עמל",
                                "SiteName": null,
                                "AllPhones": "8421630,8721003",
                                "Company": {
                                    "Id": 19,
                                    "IsActive": false,
                                    "Name": "שחף - 19",
                                    "SiteName": null,
                                    "Email": null
                                },
                                "Phones": [
                                    "8421630",
                                    "8721003"
                                ],
                                "SecurityManager": {
                                    "Id": 0,
                                    "IsActive": false,
                                    "Name": "דורון קליין",
                                    "SiteName": null,
                                    "Mobile": null,
                                    "Phone": "057-7548433"
                                },
                                "SecurityManagerName": "דורון קליין",
                                "SecurityManagerPhone": "057-7548433",
                                "StandardEndHours": [
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    "15:15",
                                    null,
                                    null
                                ],
                                "StandardStartHours": [
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    "07:15",
                                    null,
                                    null
                                ],
                                "Supervisor": {
                                    "Id": 0,
                                    "IsActive": false,
                                    "Name": "חיים",
                                    "SiteName": null,
                                    "Mobile": null,
                                    "Phone": "052-5251079"
                                },
                                "SupervisorName": "חיים",
                                "SupervisorPhone": "052-5251079",
                                "TimeZoneOffset": 180
                            },
                            "Date": "2014-04-02T15:30:41.530Z"
                        },
                        "Status": 2
                    },
                    {
                        "UniqueId": "8512b39b-85ca-4902-8101-a4f655a3149c",
                        "Date": "2014-04-02T15:31:23.318Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 2
                    },
                    {
                        "UniqueId": "4ac8ec7e-ff9e-4dfe-a631-0c0e23f988c4",
                        "Date": "2014-04-02T15:31:31.525Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 2
                    },
                    {
                        "UniqueId": "e5f68284-4a1b-480f-bd9a-3897253a4c38",
                        "Date": "2014-04-02T15:33:17.316Z",
                        "BarCode": "123",
                        "IsEnter": true,
                        "Location": {
                            "Longitude": 34.544432,
                            "Latitude": 52.44033234
                        },
                        "Employee": {
                            "Id": 35841,
                            "IsActive": true,
                            "Name": "בדיקות",
                            "SiteName": null,
                            "Mobile": "",
                            "Phone": "",
                            "AgreementNumber": 0,
                            "BreakTime": 0,
                            "BreakTimeFromHour": "-01:00",
                            "CanEditStandardHours": false,
                            "CanTypeData": false,
                            "Comments": "",
                            "Company": {
                                "Id": 32,
                                "IsActive": false,
                                "Name": "מגי - 32",
                                "SiteName": null,
                                "Email": null
                            },
                            "ContractType": 0,
                            "CutToTekenCloseLimit": 0,
                            "CutToTekenOpenLimit": 0,
                            "DailyEshelTariff": 0,
                            "DailyTariff": 0,
                            "DailyTripTariff": 0,
                            "DailyWorkHours": null,
                            "Email": "",
                            "EmpHours125Week": 0,
                            "HolidayEndHour": null,
                            "HolidayEveningEndHour": null,
                            "HolidayEveningHours": "00:00",
                            "HolidayEveningStartHour": null,
                            "HolidayFreeEndHour": null,
                            "HolidayFreeHours": "00:00",
                            "HolidayFreeStartHour": null,
                            "HolidayHours": "00:00",
                            "HolidayStartHour": null,
                            "Hours125FriStart": 0,
                            "Hours125Start": 0,
                            "ImageUrl": null,
                            "IsGlobalAddition": false,
                            "JobExtent": "00:00",
                            "MaxMonthTripTariff": 0,
                            "MaxRefCodeLength": 9,
                            "MaxYlmCodeLength": -1,
                            "NextEmployeeId": 35841,
                            "PensionTariff": 0,
                            "PersonID": "123123123",
                            "PreviousEmployeeId": 35841,
                            "RefCode": null,
                            "RoundToStandardEndHour": false,
                            "RoundToStandardStartHour": false,
                            "SalarySoftwareCode": null,
                            "SiteLockItems": [],
                            "StandardEndHours": [
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00",
                                "09:00"
                            ],
                            "StartEmploy": null,
                            "TimeZoneOffset": 180,
                            "YlmCode": "000"
                        },
                        "Site": {
                            "Id": 123,
                            "IsActive": false,
                            "Name": "עמל",
                            "SiteName": null,
                            "AllPhones": "8421630,8721003",
                            "Company": {
                                "Id": 19,
                                "IsActive": false,
                                "Name": "שחף - 19",
                                "SiteName": null,
                                "Email": null
                            },
                            "Phones": [
                                "8421630",
                                "8721003"
                            ],
                            "SecurityManager": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "דורון קליין",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "057-7548433"
                            },
                            "SecurityManagerName": "דורון קליין",
                            "SecurityManagerPhone": "057-7548433",
                            "StandardEndHours": [
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                "15:15",
                                null,
                                null
                            ],
                            "StandardStartHours": [
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                "07:15",
                                null,
                                null
                            ],
                            "Supervisor": {
                                "Id": 0,
                                "IsActive": false,
                                "Name": "חיים",
                                "SiteName": null,
                                "Mobile": null,
                                "Phone": "052-5251079"
                            },
                            "SupervisorName": "חיים",
                            "SupervisorPhone": "052-5251079",
                            "TimeZoneOffset": 180
                        },
                        "Status": 2
                    }
                ];
            });
        
	}];
})(Simple, Simple.Inspector);